### ISSUE TITLE
Ruby Syllabus 2015 Reboot

### ISSUE THREAD

**Issue by samsworldofno** [codebar/tutorials#160]
[Placeholder for this project]

I'm hoping to work with others on a rewrite of the ruby syllabus. I've taught it a few times and have found that students often (a) struggle with some of the core concepts of the language, (b) struggle with some of the practicalities like running a CLI app, and (c) want more ways to learn.

I have a bunch of opinions of my own about how to improve the syllabus, but I want this to be a collaborative effort that the Codebar community are happy with, just like any PR. So, my idea is to firstly attend Codebar and coach on the ruby syllabus for the next few weeks (I confess, I've avoided it), and then get together a group of people who could help out. We'd then discuss and agree on a general direction and guiding principles, share out the writing work and test the new syllabus in upcoming Codebar sessions.

**Comment by samsworldofno** [comment]
tagging: @andrewmcdonough

**Comment by samsworldofno** [comment]
tagging: @Najaf

**Comment by Najaf** [comment]
Thanks for tagging me into this. It would be great if you could share your findings after teaching at codebar for the next few weeks.

Before writing a syllabus/set of tutorials, it would be good to know:

* What are the motivations for a typical student learning Ruby at codebar?
* Are there any common areas where people get stuck?
* How well does the "tutorial" format work? i.e. how well do students "know" the material after completing it?

It would be good to know the above based on real interactions with beginners rather than conjecture, which is usually the only thing that senior developers like us who don't teach full-time have to go on.

**Comment by samsworldofno** [comment]
Hey Ali,

Cheers for the comment. Definitely going to plan this before jumping in and writing... but I hadn't thought about quantifying the current experience so that's a great input. I'll be certain to share my findings... and hopefully those of others!

SP

**Comment by Najaf** [comment]
I wouldn't worry too much about being 100% scientific, but I'm willing to bet even the most superficial polling of four or five newbies would be more informative than us just guessing at what we believe they should learn :)

**Comment by samsworldofno** [comment]
No chance of 100% science here :) I'll put my notes up here: https://github.com/codebar/tutorials/wiki/Ruby-Syllabus-2015-Notes. Very scribbly and not ready for review at all but better put it here in the open than hidden in google docs or somebody's head.

I've added a few from previous experiences to get started.

**Comment by creature** [comment]
Some things I've picked up while coaching at Codebar, & teaching elsewhere: 

- Codebar sessions last about 2 hours, and you can only rely on about 90 minutes of them being available. So I'd aim for each tutorial to take about 60-90 minutes.
- The tutorials are designed to be worked through with a coach, so they don't have to explain *everything*. But if they don't explain something, then a clear "Ask your coach about ______" prompt is useful. 
  - But! Some students have said things like "I tried to work through this at home on my own but I got stuck because it didn't explain something." I don't think this should be prioritised, but it's worth bearing in mind. 
- I'd really like to see more exercises included in the tutorials. I've been considering adding a companion "exercise tutorial" for each existing tutorial, that sets problems/tasks/challenges that use the material the student's just learned. 
- Most students struggle to get anything from the Ruby Koans. They're great for non-beginners coming from another language, but I've heard a lot of beginners say they just guessed at the answers until they got it right and that they didn't really learn anything. 

I can outline a general syllabus/approach I've (successfully) used when teaching beginners if you like, but I don't think there's anything special or magic about it.

**Comment by Najaf** [comment]
> I'd really like to see more exercises included in the tutorials. I've been considering adding a companion "exercise tutorial" for each existing tutorial, that sets problems/tasks/challenges that use the material the student's just learned.

Seconded. Perhaps I'm just covering up my weaknesses as a teacher, but the workshops/courses I deliver are 98% student with hands on keyboard doing exercises, occasionally asking for help. 2% me explaining things.

**Comment by samsworldofno** [comment]
Tagging: @heruku, @christophgockel

**Comment by samsworldofno** [comment]
Hi All,

I've added some more notes to the document (https://github.com/codebar/tutorials/wiki/Ruby-Syllabus-2015-Notes) based upon experiences coaching Ruby 1, 2 and 3 over the last few weeks. I'm going tonight and will try to get some exposure to 4 and 5.

After that I'll ping the group and get a discussion arranged.

SP

**Comment by samsworldofno** [comment]
... and of course, any other thoughts/observations/notes are welcome in that document, too!
