### ISSUE TITLE
Using existing learning material for topics?

### ISSUE THREAD

**Issue by lwm** [codebar/tutorials#302]
Hi there, awesome codebar humans!

I wanted to open up a discussion about using existing learning material for tutorials at codebar. The existing tutorials are great, so a big :+1: to any one who put that work in. This issue is not meant to belittle work that any one has done or yet to do! 

So, some tutorials are incomplete (see https://github.com/codebar/tutorials/issues/149) and as I can see from https://github.com/codebar/tutorials/issues/284 and https://github.com/codebar/tutorials/issues/262, the tutorials also need maintenance and improvement. A lot of work!!!

Why is codebar not using existing materials to cut down the work load? Given the world is full of really smart people, it is almost guaranteed to find some decent material on a range of topics. If it isn't great, then it could be incorporated into a more user friendly format, but at least used as a base.

The material would need to be vetted first, I suppose. Acceptance criteria could include:
  - open source and free to access for all
  - transparent process for interacting with author (to suggest improvements)

The benefits I can see are:
  - Comprehensive material for many different topics.
  - The burden of maintenance is off codebar contributors (freeing them to teach more!)

For example, for Python, there are many resources. One I've used to teach before is http://pymbook.readthedocs.io/en/latest/.

What do you think? I'd love to help if people want to move forward with that.

**Comment by kodikos** [comment]
I don't think we're totally averse to using other materials - if a student is using some other resource to learn from and wants help, we won't turn them away! I see many students using codewars, for example. Recommending materials probably should require vetting as you suggest, but I don't see an issue with us making these in further reading sections.
I think the tutorials written by codebar are for helping students who may not have even opened anything else but a browser get started on coding. They can also help the coaches have a basis for ensuring students have certain skills before proceeding to more difficult things. They are a very mild learning curve that produce results very quickly, acting as a great confidence builder.
I myself am trying to expand the PHP guides, and am involved with improving the downloads for sample files (which I'm going to try to get students to do!). But my free time is limited and it's because of this voluntary contributing that we don't always have the tutorials as refined as they could be. It's also an iterative process, students need to try them out and we learn from problems with them. We'll get there eventually :)
I think one point of issue that may need considering is how many languages we support and why - it can be tricky getting the right mix of coaches for what students want to learn, and we should question whether we're spreading ourselves too thin.
I'd say have a go at raising PR's to include links to other guides (maybe one at a time - no one likes a huge PR to review!), and mark them as needing to vet what they link to, then each one has a chance to be reviewed and discussed separately. Sound good?

**Comment by octopusinvitro** [comment]
Hi Luke,
Welcome to the tutorials repo and thank you for your feedback.

I think one issue is that the Codebar tutorials are of a very special kind, for example we want the students to build something using the tutorial, see here for the rules: <https://github.com/codebar/tutorials#general-tutorial-rule>. Also, they are thought as material to be covered in the presence and with the help of a coach, (although they can certainly follow them on their own).

Some tutorials out there follow these rules, some don't. But as @kodikos mentions, we certainly mention and point our students to material that exists out of Codebar.

**Comment by lwm** [comment]
Thanks for the prompt reply! 

I think you all agree that external resources are great and worth using, but that the tutorials are also useful and you aren't stopping anyone following either path! So, I think my issue is then that there are simply none listed on the tutorials page to guide the learner. So I will submit some PRs like @kodikos recommended.

It's a great initiative you have here. I coached last night and it was great fun.

Will close this for now and link any related PRs accordingly.
